#!/usr/bin/env python3
"""Distill the 641-D Teacher + friction estimator into one 640-D actor.

The exact friction coefficient is never exposed to the Student.  Targets are
generated by the deployable estimator followed by the frozen Oracle Teacher.
Isaac noisy-sensor rollouts provide the main distribution and labeled MuJoCo
rollouts can be repeated to close the Sim2Sim covariate gap.
"""

from __future__ import annotations

import argparse
import json
import math
import random
import shutil
import struct
from pathlib import Path

import numpy as np
import onnx
import torch
from onnx import numpy_helper
from torch import nn
from torch.utils.data import DataLoader, TensorDataset


class Actor(nn.Module):
    def __init__(self, input_dim: int):
        super().__init__()
        self.mlp = nn.Sequential(
            nn.Linear(input_dim, 512),
            nn.ELU(),
            nn.Linear(512, 256),
            nn.ELU(),
            nn.Linear(256, 128),
            nn.ELU(),
            nn.Linear(128, 29),
        )
        # Training-only auxiliary head.  It forces the 640-D backbone to retain
        # friction information; forward() remains action-only, so ONNX deploy
        # has exactly the same one-input/one-output interface.
        self.mu_head = nn.Linear(128, 1)

    def forward(self, observation: torch.Tensor) -> torch.Tensor:
        return self.mlp(observation)

    def predict_mu(self, observation: torch.Tensor) -> torch.Tensor:
        latent = self.mlp[:6](observation)
        return 1.30 * torch.sigmoid(self.mu_head(latent)).squeeze(-1)


class FrictionEstimator(nn.Module):
    def __init__(self, input_dim: int):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.ELU(),
            nn.Linear(256, 64),
            nn.ELU(),
            nn.Linear(64, 1),
        )

    def forward(self, observation: torch.Tensor) -> torch.Tensor:
        return 1.30 * torch.sigmoid(self.net(observation)).squeeze(-1)


class NormalizedEstimator(nn.Module):
    def __init__(self, checkpoint: dict):
        super().__init__()
        self.estimator = FrictionEstimator(int(checkpoint["input_dim"]))
        self.estimator.load_state_dict(checkpoint["model"])
        self.register_buffer("mean", torch.as_tensor(checkpoint["mean"], dtype=torch.float32))
        self.register_buffer("scale", torch.as_tensor(checkpoint["scale"], dtype=torch.float32))

    def forward(self, observation: torch.Tensor) -> torch.Tensor:
        return self.estimator((observation - self.mean) / self.scale)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="640-D traction policy distillation")
    parser.add_argument("--teacher-onnx", type=Path, required=True)
    parser.add_argument("--estimator-pt", type=Path, required=True)
    parser.add_argument(
        "--target-mu", choices=["privileged", "estimated"], default="privileged",
        help="Use exact training-only mu (standard Teacher distillation) or raw estimator output",
    )
    parser.add_argument("--train", type=Path, required=True)
    parser.add_argument("--test", type=Path, required=True)
    parser.add_argument("--augment", type=Path, action="append", default=[])
    parser.add_argument(
        "--augment-raw-grid", type=Path, action="append", default=[],
        help="Raw OBS1 file from a complete 5-mu x 3-speed MuJoCo matrix",
    )
    parser.add_argument(
        "--augment-repeat", type=int, default=4,
        help="Repeat every MuJoCo augmentation so it is not diluted by Isaac data",
    )
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--batch-size", type=int, default=1024)
    parser.add_argument("--learning-rate", type=float, default=2.0e-4)
    parser.add_argument("--mu-loss-coef", type=float, default=0.02)
    parser.add_argument("--resume-student", type=Path)
    parser.add_argument("--device", default="cuda:0")
    parser.add_argument("--seed", type=int, default=7750)
    parser.add_argument("--strict", action="store_true")
    parser.add_argument("--deploy-template", type=Path)
    parser.add_argument("--install-slot", type=Path)
    return parser.parse_args()


def load_actor(path: Path, input_dim: int) -> Actor:
    model = onnx.load(str(path))
    tensors = {item.name: numpy_helper.to_array(item) for item in model.graph.initializer}
    actor = Actor(input_dim)
    expected = [(0, "mlp.0"), (2, "mlp.2"), (4, "mlp.4"), (6, "mlp.6")]
    with torch.no_grad():
        for layer_index, name in expected:
            layer = actor.mlp[layer_index]
            weight = torch.from_numpy(np.array(tensors[f"{name}.weight"], copy=True))
            bias = torch.from_numpy(np.array(tensors[f"{name}.bias"], copy=True))
            if layer.weight.shape != weight.shape or layer.bias.shape != bias.shape:
                raise ValueError(
                    f"Teacher layer {name} mismatch: {tuple(weight.shape)} vs "
                    f"{tuple(layer.weight.shape)}"
                )
            layer.weight.copy_(weight)
            layer.bias.copy_(bias)
    return actor


def load_observations(path: Path) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    with np.load(path) as data:
        observation = np.asarray(data["obs"], dtype=np.float32)
        mu = np.asarray(data["mu"], dtype=np.float32).reshape(-1)
        cmd = np.asarray(data.get("cmd_vx", np.full_like(mu, np.nan)), dtype=np.float32).reshape(-1)
    if observation.ndim != 2 or observation.shape[1] not in (640, 641):
        raise ValueError(f"Expected Nx640/Nx641 observations in {path}, got {observation.shape}")
    observation = observation[:, :640]
    finite = np.isfinite(observation).all(axis=1) & np.isfinite(mu)
    return observation[finite], mu[finite], cmd[finite]


def load_raw_grid(path: Path) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Label every deploy frame, including startup, from the standard full grid."""
    payload = path.read_bytes()
    observations: list[np.ndarray] = []
    stamps: list[float] = []
    offset = 0
    while offset + 16 <= len(payload):
        magic, dim, stamp_ns = struct.unpack_from("<IIQ", payload, offset)
        offset += 16
        byte_count = int(dim) * 4
        if magic != 0x3153424F or dim not in (640, 641) or offset + byte_count > len(payload):
            raise ValueError(f"Invalid OBS1 record in {path} at byte {offset - 16}")
        observations.append(
            np.frombuffer(payload, dtype="<f4", count=dim, offset=offset).copy()[:640]
        )
        stamps.append(stamp_ns * 1.0e-9)
        offset += byte_count
    if not observations:
        raise ValueError(f"No OBS1 records in {path}")
    observation = np.stack(observations).astype(np.float32)
    stamps_np = np.asarray(stamps, dtype=np.float64)
    starts = np.r_[0, np.flatnonzero(np.diff(stamps_np) > 0.10) + 1]
    ends = np.r_[starts[1:], len(stamps_np)]
    mus = (0.08, 0.20, 0.40, 0.80, 1.20)
    speeds = (0.50, 1.00, 1.50)
    expected = len(mus) * len(speeds)
    if len(starts) != expected:
        raise ValueError(f"Expected {expected} episodes in {path}, found {len(starts)}")
    labels_mu = np.empty(len(observation), dtype=np.float32)
    labels_cmd = np.empty(len(observation), dtype=np.float32)
    for index, (start, end) in enumerate(zip(starts, ends)):
        labels_mu[start:end] = mus[index // len(speeds)]
        labels_cmd[start:end] = speeds[index % len(speeds)]
    finite = np.isfinite(observation).all(axis=1)
    return observation[finite], labels_mu[finite], labels_cmd[finite]


def initialize_student(student: Actor, teacher: Actor, nominal_mu: float = 0.50) -> None:
    """Copy the Teacher and fold a nominal mu contribution into layer-1 bias."""
    with torch.no_grad():
        student.mlp[0].weight.copy_(teacher.mlp[0].weight[:, :640])
        student.mlp[0].bias.copy_(
            teacher.mlp[0].bias + nominal_mu * teacher.mlp[0].weight[:, 640]
        )
        for index in (2, 4, 6):
            student.mlp[index].weight.copy_(teacher.mlp[index].weight)
            student.mlp[index].bias.copy_(teacher.mlp[index].bias)


def teacher_actions(
    observation: torch.Tensor,
    teacher: Actor,
    estimator: NormalizedEstimator,
    privileged_mu: torch.Tensor | None = None,
) -> torch.Tensor:
    if privileged_mu is None:
        target_mu = estimator(observation).clamp_(0.0, 1.20)
    else:
        target_mu = privileged_mu.clamp(0.0, 1.20)
    return teacher(torch.cat((observation, target_mu.unsqueeze(-1)), dim=-1))


def action_metrics(target: np.ndarray, prediction: np.ndarray) -> dict[str, float | int]:
    error = prediction - target
    abs_error = np.abs(error)
    sample_l2 = np.linalg.norm(error, axis=1)
    return {
        "samples": int(target.shape[0]),
        "mae": float(abs_error.mean()),
        "rmse": float(np.sqrt(np.square(error).mean())),
        "p95_abs": float(np.quantile(abs_error, 0.95)),
        "p95_l2": float(np.quantile(sample_l2, 0.95)),
        "max_abs": float(abs_error.max()),
    }


def evaluate(
    student: Actor,
    teacher: Actor,
    estimator: NormalizedEstimator,
    observation: np.ndarray,
    mu: np.ndarray,
    target_mode: str,
    batch_size: int,
    device: torch.device,
) -> tuple[dict[str, float | int], np.ndarray, np.ndarray]:
    loader = DataLoader(
        TensorDataset(torch.from_numpy(observation), torch.from_numpy(mu)),
        batch_size=batch_size,
    )
    targets: list[np.ndarray] = []
    predictions: list[np.ndarray] = []
    student.eval()
    teacher.eval()
    estimator.eval()
    with torch.inference_mode():
        for batch, privileged_mu in loader:
            batch = batch.to(device)
            privileged_mu = privileged_mu.to(device)
            targets.append(
                teacher_actions(
                    batch,
                    teacher,
                    estimator,
                    privileged_mu if target_mode == "privileged" else None,
                ).cpu().numpy()
            )
            predictions.append(student(batch).cpu().numpy())
    target = np.concatenate(targets)
    prediction = np.concatenate(predictions)
    return action_metrics(target, prediction), target, prediction


def install_slot(
    output_dir: Path, deploy_template: Path | None, slot: Path | None
) -> None:
    if deploy_template is None and slot is None:
        return
    if deploy_template is None or slot is None:
        raise ValueError("--deploy-template and --install-slot must be provided together")
    text = deploy_template.read_text(encoding="utf-8")
    marker = "\n  effective_friction_mu:"
    if marker not in text:
        raise ValueError(f"Teacher deploy template has no effective_friction_mu: {deploy_template}")
    # The Oracle term is deliberately the final top-level observation.  Its
    # own params/clip/scale lines are indented further and are removed too.
    prefix, _tail = text.rsplit(marker, 1)
    deploy_text = prefix.rstrip() + "\n"
    (slot / "exported").mkdir(parents=True, exist_ok=True)
    (slot / "params").mkdir(parents=True, exist_ok=True)
    shutil.copy2(output_dir / "policy.onnx", slot / "exported/policy.onnx")
    (slot / "params/deploy.yaml").write_text(deploy_text, encoding="utf-8")
    (slot / "checkpoint.txt").write_text(
        str((output_dir / "student_actor.pt").resolve()) + "\n", encoding="utf-8"
    )
    shutil.copy2(output_dir / "metrics.json", slot / "distillation_metrics.json")


def main() -> int:
    args = parse_args()
    random.seed(args.seed)
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(args.seed)
    device = torch.device(args.device if torch.cuda.is_available() else "cpu")
    args.output_dir.mkdir(parents=True, exist_ok=True)

    train_x, train_mu, train_cmd = load_observations(args.train)
    augmentation = []
    for path in args.augment:
        extra_x, extra_mu, extra_cmd = load_observations(path)
        augmentation.append({"path": str(path.resolve()), "samples": int(extra_x.shape[0])})
        for _ in range(max(args.augment_repeat, 1)):
            train_x = np.concatenate((train_x, extra_x), axis=0)
            train_mu = np.concatenate((train_mu, extra_mu), axis=0)
            train_cmd = np.concatenate((train_cmd, extra_cmd), axis=0)
    for path in args.augment_raw_grid:
        extra_x, extra_mu, extra_cmd = load_raw_grid(path)
        augmentation.append(
            {"path": str(path.resolve()), "samples": int(extra_x.shape[0]), "kind": "raw_grid"}
        )
        for _ in range(max(args.augment_repeat, 1)):
            train_x = np.concatenate((train_x, extra_x), axis=0)
            train_mu = np.concatenate((train_mu, extra_mu), axis=0)
            train_cmd = np.concatenate((train_cmd, extra_cmd), axis=0)
    test_x, test_mu, test_cmd = load_observations(args.test)

    teacher = load_actor(args.teacher_onnx, 641).to(device).eval()
    estimator_state = torch.load(args.estimator_pt, map_location="cpu", weights_only=False)
    estimator = NormalizedEstimator(estimator_state).to(device).eval()
    for parameter in teacher.parameters():
        parameter.requires_grad_(False)
    for parameter in estimator.parameters():
        parameter.requires_grad_(False)

    student = Actor(640).to(device)
    initialize_student(student, teacher)
    if args.resume_student is not None:
        resume = torch.load(args.resume_student, map_location="cpu", weights_only=False)
        missing, unexpected = student.load_state_dict(resume["model"], strict=False)
        print(
            f"resume={args.resume_student} missing={list(missing)} unexpected={list(unexpected)}",
            flush=True,
        )
    optimizer = torch.optim.AdamW(student.parameters(), lr=args.learning_rate, weight_decay=1.0e-5)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=max(args.epochs, 1), eta_min=args.learning_rate * 0.05
    )
    dataset = TensorDataset(
        torch.from_numpy(train_x), torch.from_numpy(train_mu), torch.from_numpy(train_cmd)
    )
    generator = torch.Generator().manual_seed(args.seed)
    loader = DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=True,
        generator=generator,
        num_workers=0,
        pin_memory=device.type == "cuda",
    )
    history = []
    for epoch in range(args.epochs):
        student.train()
        losses = []
        for observation, privileged_mu, command_vx in loader:
            observation = observation.to(device, non_blocking=True)
            privileged_mu = privileged_mu.to(device, non_blocking=True)
            command_vx = command_vx.to(device, non_blocking=True)
            with torch.no_grad():
                target = teacher_actions(
                    observation,
                    teacher,
                    estimator,
                    privileged_mu if args.target_mu == "privileged" else None,
                )
            prediction = student(observation)
            error = prediction - target
            # MSE preserves small action differences; SmoothL1 prevents a few
            # deployment outliers from dominating a whole epoch.
            action_loss = 0.70 * torch.mean(torch.square(error), dim=1) + 0.30 * torch.mean(
                nn.functional.smooth_l1_loss(prediction, target, beta=0.05, reduction="none"),
                dim=1,
            )
            # Stress-tail weighting retains the safe low-mu branch while
            # correcting the high-mu/high-command under-speed seen in MuJoCo.
            sample_weight = torch.ones_like(privileged_mu)
            sample_weight += (privileged_mu <= 0.25).float()
            sample_weight += (privileged_mu >= 0.75).float()
            sample_weight += 3.0 * (
                (privileged_mu >= 1.10) & (command_vx >= 1.0)
            ).float()
            loss = torch.sum(action_loss * sample_weight) / torch.sum(sample_weight)
            predicted_mu = student.predict_mu(observation)
            mu_loss = nn.functional.smooth_l1_loss(
                predicted_mu, privileged_mu, beta=0.08
            )
            loss = loss + args.mu_loss_coef * mu_loss
            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            nn.utils.clip_grad_norm_(student.parameters(), 1.0)
            optimizer.step()
            losses.append(float(loss.detach()))
        scheduler.step()
        epoch_loss = float(np.mean(losses))
        history.append(epoch_loss)
        if epoch == 0 or (epoch + 1) % 10 == 0 or epoch + 1 == args.epochs:
            print(
                f"epoch={epoch + 1:03d}/{args.epochs} loss={epoch_loss:.8f} "
                f"lr={scheduler.get_last_lr()[0]:.2e}",
                flush=True,
            )

    train_metrics, _, _ = evaluate(
        student, teacher, estimator, train_x, train_mu, args.target_mu, args.batch_size, device
    )
    test_metrics, test_target, test_prediction = evaluate(
        student, teacher, estimator, test_x, test_mu, args.target_mu, args.batch_size, device
    )
    gates = {
        "unseen_action_mae": {
            "value": test_metrics["mae"], "target": "<= 0.030", "pass": test_metrics["mae"] <= 0.030
        },
        "unseen_action_p95": {
            "value": test_metrics["p95_abs"], "target": "<= 0.080", "pass": test_metrics["p95_abs"] <= 0.080
        },
        "finite": {
            "value": bool(np.isfinite(test_prediction).all()), "target": "true",
            "pass": bool(np.isfinite(test_prediction).all()),
        },
    }
    overall = all(item["pass"] for item in gates.values())
    report = {
        "method": (
            "privileged action distillation: 640-D history -> frozen Teacher(true training-only mu)"
            if args.target_mu == "privileged"
            else "composite distillation: 640-D obs -> estimator -> frozen Teacher"
        ),
        "target_mu": args.target_mu,
        "teacher_onnx": str(args.teacher_onnx.resolve()),
        "estimator_pt": str(args.estimator_pt.resolve()),
        "input_dim": 640,
        "output_dim": 29,
        "training_samples": int(train_x.shape[0]),
        "test_samples": int(test_x.shape[0]),
        "augmentation_repeat": int(args.augment_repeat),
        "augmentation": augmentation,
        "epochs": int(args.epochs),
        "mu_loss_coef": float(args.mu_loss_coef),
        "resume_student": str(args.resume_student.resolve()) if args.resume_student else None,
        "final_loss": history[-1] if history else math.nan,
        "train": train_metrics,
        "isaac_unseen": test_metrics,
        "gates": gates,
        "overall": "PASS" if overall else "FAIL",
    }

    student = student.cpu().eval()
    torch.save(
        {
            "model": student.state_dict(),
            "input_dim": 640,
            "output_dim": 29,
            "teacher_onnx": str(args.teacher_onnx.resolve()),
            "estimator_pt": str(args.estimator_pt.resolve()),
            "metrics": report,
        },
        args.output_dir / "student_actor.pt",
    )
    example = torch.zeros((1, 640), dtype=torch.float32)
    torch.onnx.export(
        student,
        example,
        args.output_dir / "policy.onnx",
        input_names=["obs"],
        output_names=["actions"],
        opset_version=17,
    )
    np.savez_compressed(
        args.output_dir / "isaac_unseen_actions.npz",
        truth_mu=test_mu,
        command_vx=test_cmd,
        teacher_action=test_target,
        student_action=test_prediction,
    )
    (args.output_dir / "metrics.json").write_text(
        json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    install_slot(args.output_dir, args.deploy_template, args.install_slot)
    print(json.dumps(report, indent=2, ensure_ascii=False))
    print(f"overall={report['overall']} onnx={args.output_dir / 'policy.onnx'}")
    return 3 if args.strict and not overall else 0


if __name__ == "__main__":
    raise SystemExit(main())
